query DeviceQuery($name: String!) {
  NetworkDevice(name__value: $name) {
    edges {
      node {
        interfaces {
          edges {
            node {
              name {
                value
              }
              mode {
                value
              }
              status {
                value
              }
              vlan {
                edges {
                  node {
                    vlan_id {
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  NetworkVlan {
    edges {
      node {
        name {
          value
        }
        vlan_id {
          value
        }
      }
    }
  }
}
